version: "3.9"

services:
  api:
    container_name: songs-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    extra_hosts:
      # host for db connection
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV:development
    restart: unless-stopped
    command: npm run start:dev
    depends_on:
      - postgres
    env_file:
      - .env

  front:
    container_name: songs-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: npm run dev
    depends_on:
      - api
    env_file:
      - .env

  postgres:
    container_name: postgres-thingortwo
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=songs_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
